Repository caicloud/ftlib, pull requests merged in 2019-12, with the labels that each got.

#12 Fix broken links and correct spelling of ElasticDL
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#15 feat: update design docs for ftlib flow chart
  docs/design/consensus.md
  docs/design/ftlib.md
  docs/imgs/ftlib_flow.png
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#21 Add IDE-related settings to .gitignore
  .gitignore
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#20 Add script to setup k8s environment on Travis CI
  .travis.yml
  scripts/setup_k8s_env.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#23 Setup pre-commit check and fix all existing issues
  .isort.cfg
  .pre-commit-config.yaml
  .travis.yml
  Dockerfile
  ftlib/__init__.py
  ftlib/consensus/basic.py
  ftlib/consensus/consensus_status.py
  ftlib/consensus/shared_storage/__init__.py
  ftlib/consensus/shared_storage/master_server.py
  ftlib/consensus/shared_storage/utils.py
  ftlib/framework/basic.py
  ftlib/framework/dummy_nccl/__init__.py
  ftlib/framework/framework_status.py
  ftlib/framework/pytorch/__init__.py
  ftlib/ftlib_status.py
  test/generic_test.py
  test/pytorch_test.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#22 Add Travis and LICENSE badges
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#16 feat: add member list lib
  ftlib/__init__.py
  ftlib/consensus/basic.py
  ftlib/consensus/gossip/__init__.py
  ftlib/consensus/gossip/gen_shared_lib.sh
  ftlib/consensus/gossip/memberlist/go.mod
  ftlib/consensus/gossip/memberlist/go.sum
  ftlib/consensus/gossip/memberlist/main.go
  ftlib/consensus/gossip/test.py
  ftlib/consensus/shared_storage/__init__.py
  ftlib/rank_assign_scheme.py
  test/pytorch_test.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#24 Add docker image and k8s configurations for testing on Travis
  .travis.yml
  Dockerfile
  deploy/Dockerfile
  deploy/FindNCCL.cmake
  deploy/ftlib-rbac.yaml
  deploy/ftlib-test.yaml
  requirements.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#25 feat: add roadmap and update readme
  README.md
  ROADMAP.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#27 Fix typo: pytroch -> pytorch
  ftlib/__init__.py
  ftlib/framework/pytorch/__init__.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#28 Set up Python package structure and a couple fixes
  .isort.cfg
  .travis.yml
  README.md
  deploy/Dockerfile
  deploy/ftlib-test.yaml
  ftlib/ftlib_status.py
  requirements-dev.txt
  setup.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#29 Initialize master address and check None for rebuild()
  ftlib/__init__.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#30 Include proto files in .gitignore
  .gitignore
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#32 Add isort configuration to avoid conflicts with black
  .isort.cfg
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#26 feat: refactor design docs
  docs/design/communication_library.md
  docs/design/consensus.md
  docs/design/framework.md
  docs/design/ftlib.md
  docs/imgs/ftlib.png
  docs/imgs/ftlib_flow.png
  docs/imgs/role_in_distributed.png
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#34 Add NCCL broadcast op
  ftlib/framework/dummy_nccl/__init__.py
  ftlib/framework/dummy_nccl/src/fault_tolerant_lib.cxx
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#35 fix: address issues on further tests
  ftlib/commlib/pytorch/impl.py
  ftlib/impl.py
  ftlib/rank_assign_scheme.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#36 feat: add data io demo
  .isort.cfg
  ftlib/impl.py
  test/data.py
  test/pytorch-gossip-tricky-data.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#38 fix: rename wait_weights_ready to wait_gradients_ready
  test/deprecated-tests/generic_test.py
  test/deprecated-tests/pytorch_test.py
  test/pytorch-gossip/pytorch-gossip_test.py
  test/tricky-data/data.py
  test/tricky-data/pytorch-gossip-tricky-data.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
