Repository caicloud/ftlib, pull requests merged in 2020-02, with the labels that each got.

#46 Fix the Dockerfile used for FTLib example on k8s
  test/kubernetes/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#47 fix issue on logging, error handling and timing
  ftlib/impl.py
  ftlib/rank_assign_scheme.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#49 feat: increase stability of ftlib.rebuild
  ftlib/commlib/pytorch/impl.py
  ftlib/consensus/gossip/impl.py
  ftlib/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#50 fix: address issue when work lost and re-wrap ddp model
  ftlib/commlib/pytorch/impl.py
  ftlib/consensus/gossip/memberlist/main.go
  test/kubernetes/script/main.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#52 Udpate example
  ftlib/commlib/pytorch/impl.py
  ftlib/consensus/gossip/impl.py
  ftlib/impl.py
  test/kubernetes/Dockerfile
  test/kubernetes/script/main.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#53 feat: replace dummy date+lenet with a polynomial example
  ftlib/utils/kubernetes/__init__.py
  ftlib/utils/kubernetes/svc.py
  test/kubernetes/script/main.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#54 fix: python print not showing in docker
  test/kubernetes/ftlib-deployment.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#55 fix: address rank-assign issue
  ftlib/impl.py
  ftlib/rank_assign_scheme.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#56 fix: update demo script after ftlib code changes
  test/pytorch-gossip/pytorch-gossip_test.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
