Repository caicloud/ftlib, pull requests merged in 2020-01, with the labels that each got.

#39 Fix typo: sefl -> self
  ftlib/consensus/gossip/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#37 Expose and register NCCL APIs
  deploy/Dockerfile
  ftlib/commlib/dummy_nccl/__init__.py
  ftlib/commlib/nccl/CMakeLists.txt
  ftlib/commlib/nccl/__init__.py
  ftlib/commlib/nccl/build_with_pybind11.sh
  ftlib/commlib/nccl/impl.py
  ftlib/commlib/nccl/src/fault_tolerant_lib.cxx
  ftlib/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#40 fix: build when ftlib is initialized
  ftlib/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#41 Fix a couple of issues in implementations
  docs/design/ftlib.md
  ftlib/commlib/nccl/impl.py
  ftlib/impl.py
  test/deprecated-tests/generic_test.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#44 feat: add kubernetes example
  ftlib/commlib/pytorch/impl.py
  ftlib/consensus/gossip/impl.py
  ftlib/consensus/gossip/test.py
  ftlib/impl.py
  test/kubernetes/Dockerfile
  test/kubernetes/ftlib-deployment.yaml
  test/kubernetes/script/main.py
  test/kubernetes/script/test.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
