Repository caicloud/ftlib, pull requests merged in 2020-03, with the labels that each got.

#58 feat: wrap torch api for numpy ndarray
  ftlib/commlib/pytorch/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#59 feat: wrap torch api for numpy ndarray (#58)
  ftlib/commlib/pytorch/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#60 feat: update nccl communication library
  ftlib/commlib/nccl/CMakeLists.txt
  ftlib/commlib/nccl/Dockerfile
  ftlib/commlib/nccl/Dockerfile.cn
  ftlib/commlib/nccl/build_with_pybind11.sh
  ftlib/commlib/nccl/impl.py
  ftlib/commlib/nccl/src/fault_tolerant_lib.cxx
  ftlib/commlib/pytorch/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#61 Fix CI: remove already deleted build_with_pybind11.sh
  deploy/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#62 feat: add gloo support with numpy
  ftlib/commlib/gloo/CMakeLists.txt
  ftlib/commlib/gloo/Dockerfile
  ftlib/commlib/gloo/__init__.py
  ftlib/commlib/gloo/impl.py
  ftlib/commlib/gloo/src/gloo_lib.cxx
  ftlib/commlib/nccl/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#63 Fix pre-commit check in Gloo implementation
  ftlib/commlib/gloo/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#65 feat: add custom option when init memberlist
  ftlib/consensus/gossip/impl.py
  ftlib/consensus/gossip/memberlist/main.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#66 feat: add option for tcp_timeout
  ftlib/consensus/gossip/impl.py
  ftlib/consensus/gossip/memberlist/main.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#68 Custom config memberlist
  ftlib/consensus/gossip/impl.py
  ftlib/consensus/gossip/memberlist/main.go
  ftlib/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#70 fix: restore the old rank assign scheme
  ftlib/impl.py
  ftlib/rank_assign_scheme.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#71 feat: update OWNER file
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#72 feat: update grad_sync_done
  ftlib/commlib/pytorch/impl.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
